version: '3.8'

services:
  client:
    build: ./client
    ports:
      - "5173:5173"
    networks:
      - f_brain_network

  server:
    build: ./server
    ports:
      - "8000:8000"
    networks:
      - f_brain_network

  prometheus:
    build: ./monitoring/prometheus
    volumes:
      - ./monitoring/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - f_brain_network

  grafana:
    build: ./monitoring/grafana
    ports:
      - "3000:3000"
    networks:
      - f_brain_network

  proxy:
    build: ./proxy
    ports:
      - "80:80"
    depends_on:
      - client
      - server
    networks:
      - f_brain_network




networks:
  f_brain_network:
    driver: bridge
